class FeatureFlags {
  static const MOODLE_ENABLED = "MOODLE_ENABLED";
    static const MOODLE_PAGE_ENABLED = "MOODLE_PAGE_ENABLED";
  static const INTELLIGENT_GRADE_VIEW_ENABLED =
      "INTELLIGENT_GRADE_VIEW_ENABLED";
    static const MATRIX_SHOW_DEBUG = "SHOW_MATRIX_DEBUG";
    // used for moodle as well
    static const MATRIX_SHOW_CREATE_ROOM = "SHOW_MATRIX_CREATE_ROOM";
    static const MATRIX_SHOW_DEV_SETTINGS = "MATRIX_SHOW_DEV_SETTINGS";
    static const MATRIX_ENABLE_SENDING_POLLS = "MATRIX_ENABLE_SENDING_POLLS";

    static const USE_NEW_DRAWER = "USE_NEW_DRAWER";
}
