// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs8fbLTZJrnqIY1SRKJm_vDy4Zuhs5U9g',
    appId: '1:365970918966:web:903666471c3cd73c1d1297',
    messagingSenderId: '365970918966',
    projectId: 'angergymapp',
    authDomain: 'angergymapp.firebaseapp.com',
    storageBucket: 'angergymapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWMyojzCYnP8O16ZYzS9O1ju6rcsvLcLI',
    appId: '1:365970918966:android:6bed71b9b31ec5511d1297',
    messagingSenderId: '365970918966',
    projectId: 'angergymapp',
    storageBucket: 'angergymapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3l8p6C0W_8MxAE-_aPtjNyNdn9aGUio0',
    appId: '1:365970918966:ios:4229c968dcc9951c1d1297',
    messagingSenderId: '365970918966',
    projectId: 'angergymapp',
    storageBucket: 'angergymapp.appspot.com',
    iosClientId: '365970918966-nk5u9sd50qrdmj5p7f7n3fleh9j9r9p7.apps.googleusercontent.com',
    iosBundleId: 'com.robertstuendl.angerapp',
  );
}
