name: Build & deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: app

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: "2.10.3"

    - name: Get dependencies
      run: flutter pub get

      # - name: Test project
      #   run: flutter test

    - name: Build release project
      run: flutter build apk

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: Android App
        path: ./app/build/app/outputs/flutter-apk/app-release.apk
        
  build-web:
    name: Build Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.10.3"

      - name: Get dependencies
        run: flutter pub get

      # - name: Test project
      #   run: flutter test

      - name: Build release project
        run: flutter build web --web-renderer html

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./app/build/web

  deploy:
    name: Deploy-Web
    needs: build-web
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: angergymapp.robertstuendl.com
